### ISSUE TITLE
unsure usage

### ISSUE THREAD

**Issue by cmeesters** [snakemake/snakemake-storage-plugin-fs#7]
Finally got to trying the profile with the storage plugin. With a setup analogue to the sample in the docs:

```
default-storage-provider: fs
shared-fs-usage:
  - persistence
  - sources
  - source-cache
local-storage-prefix: /localscratch/$SLURM_JOB_ID
```
and the current release 0.1.5 , I get 

```
WorkflowError:
Failed to create local storage prefix /localscratch/$SLURM_JOB_ID/fs
PermissionError: [Errno 13] Permission denied: '/localscratch/$SLURM_JOB_ID'
```
This is logical: snakemake is invoked on the head node of a cluster, the selected storage prefix only exists in a job context. The aim is to stage-in input files in a slurm job context. Hence, the stage-in needs to be delayed until the job starts. Which is the way to achieve this? (The profile yaml exists on a global parallel file system.)

**Comment by johanneskoester** [comment]
So, you basically need different values for that parameter depending on the host machine. If the variable is available, you need that path, if not (on the login node) you need a different path (e.g. /tmp/...).

Snakemake profiles can be templated with [YTE](https://yte-template-engine.github.io), see [here](https://snakemake.readthedocs.io/en/stable/executing/cli.html#use-templating-in-profiles) :-)!

Just do somehting like this:

```yaml
__use_yte__: True

__definitions__:
  - import os

default-storage-provider: fs
shared-fs-usage:
  - persistence
  - sources
  - source-cache
?if "SLURM_JOB_ID" in os.environ:
    local-storage-prefix: /localscratch/$SLURM_JOB_ID
?else:
    local-storage-prefix: /tmp/$USER/snakemake
```
